[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:horizon]
process_name=%(program_name)s
command=php /var/www/artisan horizon
directory=/var/www
user=laravel
numprocs=1
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
